### ISSUE TITLE
[TL 4] Task List Information

### ISSUE THREAD

**Issue by flomich** [sw21-tug/Team_26#4]
### User Story
**As a** User,
**I want to**  see the name, the date and the remaining time for each task in the list of my tasks
**so that** I can quickly see which tasks i have to do next and how much time is left.

### Acceptance Criteria

- [ ] The *task view* shows a list of all tasks in chronological order
- [ ] The user can scroll through the list. 
- [ ] Each list item shows a task with its name, the date, and the remaining time
